import { CFCustomer } from "../../CommonTypes";

// Add Customer Types
export interface AddCustomerParams {
    // We require all fields except those generated by the server/database
    customer: Omit<CFCustomer, '_id' | 'createdAt' | 'updatedAt'>;
}

export interface AddCustomerResponse {
    success: boolean;
    customer: CFCustomer;
    timestamp: string;
}

export type AddCustomer = (params: AddCustomerParams) => Promise<AddCustomerResponse>;
