name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint-prettier-test:
    uses: Final-Commerce/central-ops/.github/workflows/lint-prettier-test.yml@main
    secrets: inherit
