name: Publish to Artifact Registry

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    uses: Final-Commerce/central-ops/.github/workflows/publish-package.yml@main
    secrets: inherit
