name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    uses: Final-Commerce/central-ops/.github/workflows/publish-package.yml@main
    with:
      publish_npm: true
      commit_version: true
      node_version: '22'
      scope: '@final-commerce'
    secrets: inherit
